- name: Local "CI/CD" pipeline for Flask app
  hosts: localhost
  gather_facts: false
  vars:
    project_root: "{{ playbook_dir }}"
    production_base: "/mnt/c/Midterm(DevOps)/production"
    envs:
      - blue
      - green

  tasks:
    # 0. Ensure production/ exists for live link
    - name: Ensure production directory exists
      file:
        path: "{{ production_base }}"
        state: directory

    # 1. Check if live symlink exists
    - name: Stat the live symlink
      stat:
        path: "{{ production_base }}/live"
        follow: false
      register: live_stat

    # 2. Determine current_env from link (blue or green)
    - name: Set current_env from existing symlink
      set_fact:
        current_env: "{{ live_stat.stat.lnk_source | basename }}"
      when: live_stat.stat.exists and live_stat.stat.islnk

    - name: Initialize current_env to empty if live missing
      set_fact:
        current_env: ""
      when: not live_stat.stat.exists

    # 3. Pick next_env color
    - name: Pick next color (blue ↔ green)
      set_fact:
        next_env: "{{ envs[1] if current_env == envs[0] else envs[0] }}"

    # 4. Prepare target environment directory
    - name: Ensure target env directory exists
      file:
        path: "{{ production_base }}/{{ next_env }}"
        state: directory

    - name: Copy app folder into target environment
      synchronize:
        src: "{{ project_root }}/app"
        dest: "{{ production_base }}/{{ next_env }}"
        recursive: yes
        delete: yes

    - name: Copy venv into target environment
      synchronize:
        src: "{{ project_root }}/venv"
        dest: "{{ production_base }}/{{ next_env }}"
        recursive: yes
        delete: yes

    - name: Copy run.py into target environment
      synchronize:
        src: "{{ project_root }}/run.py"
        dest: "{{ production_base }}/{{ next_env }}"
        recursive: yes
        delete: yes

    - name: Kill any old Flask process
      shell: |
        if [ -f "{{ production_base }}/{{ current_env }}/flask.pid" ]; then
          kill "$(cat '{{ production_base }}/{{ current_env }}/flask.pid')" \
            && rm '{{ production_base }}/{{ current_env }}/flask.pid'
        else
          pkill -f '{{ production_base }}/{{ current_env }}/run.py' || true
        fi
      ignore_errors: true
      when: current_env != ""

    # 8. Switch live symlink to the new env
    - name: Switch live symlink to the new env
      file:
        src: "{{ production_base }}/{{ next_env }}"
        dest: "{{ production_base }}/live"
        state: link
        force: yes

      # 9. Run Flask app and record its PID
    - name: Run Flask app
      shell: |
        nohup "{{ production_base }}/live/venv/bin/python3" "{{ production_base }}/live/run.py" \
          > /dev/null 2>&1 &
        echo $! > "{{ production_base }}/live/flask.pid"
      async: 0
      poll: 0
